name: Deploy to Server

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/sciplot  # Adjust to your project directory
            git pull origin main
            sudo docker build -t sciplot .
            sudo docker stop sciplot || true
            sudo docker rm sciplot || true
            sudo docker run -d --name sciplot -p 8000:8000 sciplot
